name: Publish

on:
  pull_request:

permissions: {}

env:
  IMAGE_NAME: RonaldPhilipsen/gaggiuino-exporter

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write # Required for adding the labels to the PR
      issues: write # Required for adding labels to the repository
      packages: write # Required for pushing the Docker image to GitHub Packages

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Go 1.25.8
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.8

      - name: Calculate version
        id: semVersie
        uses: RonaldPhilipsen/semVersie@v2.2.0
        with:
          add-pr-label: true

      - name: Install dependencies
        run: go get .

      - name: Build
        env:
          VERSION: ${{ steps.semVersie.outputs.tag }}
          GIT_SHA: ${{ github.sha }}
        run: |
          go build \
            -ldflags="-s -w -extldflags '-static' -X 'main.BuildVersion=$VERSION' -X 'main.BuildCommitSha=$GIT_SHA' -X 'main.BuildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')'" \
            -o dist/gaggiuino-exporter

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and Push Docker Image
        if: ${{ steps.semVersie.outputs.tag }}
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: ${{ (steps.semVersie.outputs.release == 'true' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == 'true') || steps.semVersie.outputs.prerelease == 'true' }}
          provenance: mode=max
          tags: ronaldphilipsen/gaggiuino-exporter:${{ steps.semVersie.outputs.tag }}

      # If the PR is merged to main, we want to create a release and tag it.
      - name: Tag Release
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git tag ${{ steps.semVersie.outputs.tag }}
          git push origin ${{ steps.semVersie.outputs.tag }}
      - name: Create Release
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.semVersie.outputs.tag }} \
            --title '${{ steps.semVersie.outputs.tag }}' \
            --notes '${{ steps.semVersie.outputs.release-notes }}' \
            $([[ '${{ steps.semVersie.outputs.prerelease }}' == 'true' ]] && echo '--prerelease' || echo '') \
            dist/gaggiuino-exporter
