name: Publish

on:
  pull_request:
    types:
      - opened
      - closed
      - edited
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main  
permissions: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME:  ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required for adding the labels to the PR
      attestations: write # Required for pushing the SBOM and provenance to GitHub Container Registry
      id-token: write # Required for pushing the SBOM and provenance to GitHub Container Registry
      issues: write # Required for adding labels to the repository
      packages: write # Required for pushing the Docker image to GitHub Packages

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Go 1.25.8
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.8

      - name: Calculate version
        id: semVersie
        uses: RonaldPhilipsen/semVersie@v2.2.0
        with:
          add-pr-label: true

      - name: Install dependencies
        run: go get .

      - name: Build
        env:
          VERSION: ${{ steps.semVersie.outputs.tag }}
          GIT_SHA: ${{ github.sha }}
        run: |
          go build \
            -ldflags="-s -w -extldflags '-static' -X 'main.BuildVersion=$VERSION' -X 'main.BuildCommitSha=$GIT_SHA' -X 'main.BuildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')'" \
            -o dist/gaggiuino-exporter

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: ${{ (steps.semVersie.outputs.release == 'true' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == 'true') || steps.semVersie.outputs.prerelease == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        if: ${{ (steps.semVersie.outputs.release == 'true' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == 'true') || steps.semVersie.outputs.prerelease == 'true' }}
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      # If the PR is merged to main, we want to create a release and tag it.
      - name: Tag Release
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git tag ${{ steps.semVersie.outputs.tag }}
          git push origin ${{ steps.semVersie.outputs.tag }}
      - name: Create Release
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.semVersie.outputs.tag }} \
            --title '${{ steps.semVersie.outputs.tag }}' \
            --notes '${{ steps.semVersie.outputs.release-notes }}' \
            $([[ '${{ steps.semVersie.outputs.prerelease }}' == 'true' ]] && echo '--prerelease' || echo '') \
            dist/gaggiuino-exporter
