name: Qualify

on:
  push:
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required for adding the labels to the PR
      issues: write # Required for adding labels to the repository

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: 1.26.6

      - name: Calculate version
        id: semVersie
        uses: RonaldPhilipsen/semVersie@41233349edfb40f4e6da4251fea7684026182dc9 # v2.3.4
        with:
          add-pr-label: true

      - name: Install dependencies
        run: go get .

      - name: Build
        env:
          VERSION: ${{ steps.semVersie.outputs.tag }}
          GIT_SHA: ${{ github.sha }}
          PACKAGE: github.com/RonaldPhilipsen/gaggiuino-exporter
        run: |
          go build \
            -ldflags="-s -w -extldflags '-static' -X '$PACKAGE/build.BuildVersion=$VERSION' -X '$PACKAGE/build.BuildCommitSha=$GIT_SHA'" \
            -o dist/gaggiuino-exporter

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read # only needed for private or internal repos
      actions: read # only needed for private or internal repos
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
