name: Qualify

on:
  push:
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required for adding the labels to the PR
      issues: write # Required for adding labels to the repository

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: 1.26.2

      - name: Calculate version
        id: semVersie
        uses: RonaldPhilipsen/semVersie@1a62a41664cd24926fa998c29376c82796c30905 # v2.3.1
        with:
          add-pr-label: true

      - name: Install dependencies
        run: go get .

      - name: Build
        env:
          VERSION: ${{ steps.semVersie.outputs.tag }}
          GIT_SHA: ${{ github.sha }}
          PACKAGE: github.com/RonaldPhilipsen/gaggiuino-exporter
        run: |
          go build \
            -ldflags="-s -w -extldflags '-static' -X '$PACKAGE/build.BuildVersion=$VERSION' -X '$PACKAGE/build.BuildCommitSha=$GIT_SHA'" \
            -o dist/gaggiuino-exporter

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read # only needed for private or internal repos
      actions: read # only needed for private or internal repos
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
