name: Release

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Setup Go 1.25.8
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.1

      - name: Calculate version
        id: semVersie
        uses: RonaldPhilipsen/semVersie@v2.3.0

      - name: Install dependencies
        run: go get .

      - name: Build
        env:
          VERSION: ${{ steps.semVersie.outputs.tag }}
          GIT_SHA: ${{ github.sha }}
        run: |
          go build \
            -ldflags="-s -w -extldflags '-static' -X 'main.BuildVersion=$VERSION' -X 'main.BuildCommitSha=$GIT_SHA' -X 'main.BuildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')'" \
            -o dist/gaggiuino-exporter

      - name: Tag Release
        if: ${{ steps.semVersie.outputs.release == 'true' || steps.semVersie.outputs.prerelease == 'true' }}
        run: |
          git tag ${{ steps.semVersie.outputs.tag }}
          git remote set-url origin https://git:${{ secrets.TAG_PUSH_PAT }}@github.com/${{ github.repository }}
          git push origin ${{ steps.semVersie.outputs.tag }}

      - name: Create Release
        if: ${{ steps.semVersie.outputs.release == 'true' || steps.semVersie.outputs.prerelease == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.TAG_PUSH_PAT }}
        run: |
          gh release create ${{ steps.semVersie.outputs.tag }} \
            --title '${{ steps.semVersie.outputs.tag }}' \
            --notes '${{ steps.semVersie.outputs.release-notes }}' \
            $([[ '${{ steps.semVersie.outputs.prerelease }}' == 'true' ]] && echo '--prerelease' || echo '') \
            dist/gaggiuino-exporter
