name: Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  version:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.semVersie.outputs.tag }}
      release: ${{ steps.semVersie.outputs.release }}
      prerelease: ${{ steps.semVersie.outputs.prerelease }}
      release_notes: ${{ steps.semVersie.outputs.release-notes }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Calculate version
        id: semVersie
        uses: RonaldPhilipsen/semVersie@5e6e0f14dc4541ab5e740211db817961d9741b8d # v2.3.2

  release:
    if: ${{ needs.version.outputs.release == 'true' || needs.version.outputs.prerelease == 'true' }}
    needs:
      - version
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: ${{ needs.version.outputs.prerelease == 'true' && 'dev' || 'prod' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go 1.25.8
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: 1.26.4

      - name: Install dependencies
        run: go get .

      - name: Build
        env:
          VERSION: ${{ needs.version.outputs.tag }}
          GIT_SHA: ${{ github.sha }}
          CGO_ENABLED: 0
          GOOS: linux
        run: |
          go build \
            -ldflags="-s -w -extldflags '-static' -X 'main.BuildVersion=$VERSION' -X 'main.BuildCommitSha=$GIT_SHA'" \
            -o dist/gaggiuino-exporter

      - name: Tag Release
        env:
          TAG: ${{ needs.version.outputs.tag }}
          GITHUB_TOKEN: ${{ secrets.TAG_PUSH_PAT }}
        run: |
          git tag "$TAG"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}
          git push origin "$TAG"

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.TAG_PUSH_PAT }}
          TAG: ${{ needs.version.outputs.tag }}
          RELEASE_NOTES: ${{ needs.version.outputs.release_notes }}
          PRERELEASE: ${{ needs.version.outputs.prerelease }}
        run: |
          if [ "$PRERELEASE" = 'true' ]; then
            gh release create "$TAG" --title "$TAG" --notes "$RELEASE_NOTES" --prerelease dist/gaggiuino-exporter
          else
            gh release create "$TAG" --title "$TAG" --notes "$RELEASE_NOTES" dist/gaggiuino-exporter
          fi
